import logo from '@/assets/cmrl-logo.png'
import { STATUS_LABELS } from '../constants'
import type { DiaryStatus, Person, ShiftCode, ShiftDiary } from '../types'
import { formatFormDate, formatStamp } from '../utils'

export interface SummaryTableSheetProps {
  diaries: ShiftDiary[]
  stationName: string
  stationCode: string
  from: string
  to: string
  shift: ShiftCode | ''
  status: DiaryStatus | ''
  generatedBy: Person
  generatedAt?: string
}

const CELL = 'border border-paper-line px-2 py-1.5 align-middle'
const KEY = `${CELL} bg-paper-head font-semibold text-[0.6875rem]`

/**
 * Official CMRL Shift Summary Table Sheet.
 * Displays the Shift Summary Table in the official CMRL template format (CMRL/OPER/SO/R-01).
 * Used for on-screen preview in the export dialog and for physical printouts.
 */
export function SummaryTableSheet({
  diaries,
  stationName,
  stationCode,
  from,
  to,
  shift,
  status,
  generatedBy,
  generatedAt,
}: SummaryTableSheetProps) {
  const at = generatedAt ?? formatStamp(new Date().toISOString())

  return (
    <article
      aria-label={`Shift Summary Register, ${formatFormDate(from)} to ${formatFormDate(to)}`}
      className="relative isolate flex w-full max-w-[56rem] flex-col gap-2.5 overflow-hidden border border-paper-line/70 bg-paper p-4 text-[0.6875rem] leading-snug text-paper-ink shadow-sm sm:p-5"
    >
      <div aria-hidden className="pointer-events-none absolute inset-0 -z-10 grid place-items-center">
        <img src={logo} alt="" className="w-1/2 max-w-80 opacity-[0.06]" />
      </div>

      <table className="w-full border-collapse border border-paper-line">
        <tbody>
          <tr>
            <td className={`${CELL} w-[12%] p-2 text-center align-middle`}>
              <img src={logo} alt="CMRL" className="mx-auto size-11 object-contain" />
            </td>
            <td className={`${CELL} w-[66%] p-2 text-center align-middle`}>
              <p className="text-[0.9375rem] font-bold tracking-wide text-paper-brand">CHENNAI METRO RAIL LIMITED</p>
              <p className="text-[0.6875rem] font-semibold tracking-wider text-paper-muted uppercase">
                STATION SHIFT DIARY REGISTER — SHIFT SUMMARY
              </p>
              <p className="mt-0.5 text-[0.8125rem] font-semibold">
                {stationName} ({stationCode})
              </p>
            </td>
            <td className={`${CELL} w-[22%] p-2 align-middle text-[0.625rem] leading-normal whitespace-nowrap`}>
              <span className="font-semibold text-paper-muted">REF:</span> CMRL/OPER/SO/R-01
              <br />
              <span className="font-semibold text-paper-muted">PERIOD:</span> {formatFormDate(from)} to{' '}
              {formatFormDate(to)}
              <br />
              <span className="font-semibold text-paper-muted">RECORDS:</span> {diaries.length} shift
              {diaries.length === 1 ? '' : 's'}
            </td>
          </tr>
        </tbody>
      </table>

      <table className="w-full border-collapse border border-paper-line">
        <tbody>
          <tr>
            <td className={`${KEY} w-[15%]`}>Shift Filter</td>
            <td className={`${CELL} w-[35%]`}>{shift ? `Shift ${shift}` : 'All shifts'}</td>
            <td className={`${KEY} w-[15%]`}>Status Filter</td>
            <td className={`${CELL} w-[35%]`}>{status ? STATUS_LABELS[status] : 'All statuses'}</td>
          </tr>
          <tr>
            <td className={`${KEY} w-[15%]`}>Generated By</td>
            <td className={`${CELL} w-[35%]`}>
              {generatedBy.name} ({generatedBy.employeeId})
            </td>
            <td className={`${KEY} w-[15%]`}>Generated On</td>
            <td className={`${CELL} w-[35%]`}>{at}</td>
          </tr>
        </tbody>
      </table>

      <table className="w-full border-collapse border border-paper-line">
        <thead>
          <tr className="bg-paper-head text-[0.6875rem] font-semibold">
            <th className={`${CELL} text-left`}>Date</th>
            <th className={`${CELL} text-center`}>Shift</th>
            <th className={`${CELL} text-left`}>Station Controller</th>
            <th className={`${CELL} text-center`}>Entries</th>
            <th className={`${CELL} text-left`}>Status</th>
            <th className={`${CELL} text-left`}>Handed Over By</th>
            <th className={`${CELL} text-left`}>Taken Over By</th>
          </tr>
        </thead>
        <tbody>
          {diaries.length === 0 ? (
            <tr>
              <td colSpan={7} className={`${CELL} py-8 text-center text-paper-muted`}>
                No shifts match the selected filters.
              </td>
            </tr>
          ) : (
            diaries.map((d) => (
              <tr key={d.id} className="break-inside-avoid">
                <td className={`${CELL} font-medium whitespace-nowrap`}>{formatFormDate(d.date)}</td>
                <td className={`${CELL} text-center font-semibold`}>{d.shift}</td>
                <td className={CELL}>
                  <span className="font-medium">{d.controller?.name ?? '—'}</span>
                  {d.controller && (
                    <span className="block text-[0.5625rem] text-paper-muted">{d.controller.employeeId}</span>
                  )}
                </td>
                <td className={`${CELL} text-center tabular-nums`}>{d.entries.length}</td>
                <td className={CELL}>{STATUS_LABELS[d.status]}</td>
                <td className={CELL}>
                  <span>{d.handover.handedAt ? d.handover.handedBy?.name : '—'}</span>
                  {d.handover.handedAt && (
                    <span className="block text-[0.5625rem] text-paper-muted">{formatStamp(d.handover.handedAt)}</span>
                  )}
                </td>
                <td className={CELL}>
                  <span>{d.handover.takenBy?.name ?? '—'}</span>
                  {d.handover.takenBy && !d.handover.takenAt && (
                    <span className="block text-[0.5625rem] font-medium text-paper-alert">
                      Awaiting acknowledgement
                    </span>
                  )}
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>

      <div className="flex items-center justify-between border-t border-paper-line pt-2 text-[0.5625rem] text-paper-muted">
        <span>
          Generated from ODMS by {generatedBy.name} ({generatedBy.employeeId}) · Official Station Operations Register
        </span>
        <span>CMRL Official Form · Station Operations</span>
      </div>
    </article>
  )
}
