import { cellText, formatFormDate, formatPeriod, formatStampSeconds } from './format'
import { fillPlaceholders, placeholderValues } from './header/placeholders'
import { sourceReference } from './header/resolveHeader'
import type {
  ExportContext,
  ExportColumn,
  HeaderContent,
  HeaderLayout,
  Orientation,
  ReportDefinition,
  TemplateSource,
} from './types'

/** A4 width in rem at 96 dpi (210 / 297 mm). */
export const PAGE_REM = { portrait: 49.625, landscape: 70.1875 } as const

/** Locked: never part of a template. */
export const ORGANISATION = 'CHENNAI METRO RAIL LIMITED'

export interface LabelValue {
  label: string
  value: string
}

export interface LayoutColumn {
  id: string
  header: string
  /** Percentage of the table width, e.g. "14.29%". */
  width: string
  weight: number
  align: 'left' | 'center' | 'right'
}

export interface LayoutCell {
  text: string
  sub?: string
}

/**
 * The finished report: only plain strings, no placeholders left. The HTML sheet (preview + print), the PDF and
 * the Excel header all draw from this one object, so they can't drift apart.
 */
export interface ReportLayout {
  documentTitle: string
  orientation: Orientation
  header: {
    layout: HeaderLayout
    organisation: string
    title: string
    subtitle: string
    department: string
    docControl: LabelValue[]
    runDetails: LabelValue[]
  }
  columns: LayoutColumn[]
  rows: { key: string; cells: LayoutCell[] }[]
  /** All matching rows, even when `rows` is cut for a preview. */
  totalRows: number
  footer: { generated: string; reference: string }
}

/** The same run details on every document. */
function runDetails(context: ExportContext): LabelValue[] {
  return [
    { label: 'Station', value: `${context.station.name} (${context.station.code})` },
    { label: 'Period', value: formatPeriod(context.period) },
    { label: 'Filters', value: context.filters.map((f) => `${f.label}: ${f.value}`).join(' · ') || 'None' },
    { label: 'Records', value: String(context.records) },
    { label: 'Generated by', value: `${context.generatedBy.name} (${context.generatedBy.employeeId})` },
    { label: 'Generated on', value: formatStampSeconds(context.generatedAt) },
  ]
}

function layoutColumns<T>(columns: ExportColumn<T>[]): LayoutColumn[] {
  const total = columns.reduce((sum, c) => sum + (c.width ?? 10), 0)
  return columns.map((c) => ({
    id: c.id,
    header: c.header,
    weight: c.width ?? 10,
    width: `${(((c.width ?? 10) / total) * 100).toFixed(2)}%`,
    align: c.align ?? 'left',
  }))
}

export interface BuildLayoutInput<T> {
  report: ReportDefinition<T>
  rows: T[]
  rowKey: (row: T) => string
  context: ExportContext
  content: HeaderContent
  source: TemplateSource
  /** Cut the rows for an on-screen preview. Files and print always get every row. */
  rowLimit?: number
}

export function buildReportLayout<T>({
  report,
  rows,
  rowKey,
  context,
  content,
  source,
  rowLimit,
}: BuildLayoutInput<T>): ReportLayout {
  const values = placeholderValues(context, report)
  const fill = (text: string) => fillPlaceholders(text, values).trim()

  // Fixed per report in code; layout, title, subtitle and department come from the saved template.
  const fixed = report.header ?? {}
  const docControl: LabelValue[] = []
  if (fixed.formRef) docControl.push({ label: 'Form ref', value: fixed.formRef })
  if (fixed.revision) docControl.push({ label: 'Rev', value: fixed.revision })
  if (fixed.issueDate) docControl.push({ label: 'Issue date', value: formatFormDate(fixed.issueDate) })

  const title = fill(content.title) || report.name
  const shown = rowLimit === undefined ? rows : rows.slice(0, rowLimit)

  return {
    documentTitle: `${title} · ${context.station.code}`,
    orientation: fixed.orientation ?? 'portrait',
    header: {
      layout: content.layout,
      organisation: ORGANISATION,
      title,
      subtitle: fill(content.subtitle),
      department: fill(content.department),
      docControl,
      runDetails: runDetails(context),
    },
    columns: layoutColumns(report.columns),
    rows: shown.map((row) => ({
      key: rowKey(row),
      cells: report.columns.map((c) => ({ text: cellText(c, row) || '—', sub: c.sub?.(row) || undefined })),
    })),
    totalRows: rows.length,
    footer: {
      generated: `Generated from ODMS by ${context.generatedBy.name} (${context.generatedBy.employeeId}) on ${formatStampSeconds(context.generatedAt)}`,
      reference: sourceReference(report.code, source),
    },
  }
}

/** Run details two to a row, as label/value/label/value — the same in HTML and PDF. */
export function pairRows(items: LabelValue[]): LabelValue[][] {
  const rows: LabelValue[][] = []
  for (let i = 0; i < items.length; i += 2) rows.push(items.slice(i, i + 2))
  return rows
}
