import { formatFormDate, formatStampSeconds } from '../format'
import { HEADER_TEXT_FIELDS, type ExportContext, type HeaderContent } from '../types'

export const PLACEHOLDERS = [
  { key: 'station.name', label: 'Station name' },
  { key: 'station.code', label: 'Station code' },
  { key: 'register.name', label: 'Register name' },
  { key: 'register.code', label: 'Register code' },
  { key: 'period.from', label: 'Period from' },
  { key: 'period.to', label: 'Period to' },
  { key: 'records', label: 'Record count' },
  { key: 'generated.by', label: 'Generated by' },
  { key: 'generated.at', label: 'Generated date & time' },
] as const

export type PlaceholderKey = (typeof PLACEHOLDERS)[number]['key']

const KNOWN = new Set<string>(PLACEHOLDERS.map((p) => p.key))
const TOKEN = /\{([^{}]*)\}/g

export const MAX_FIELD_LENGTH = 160

export type HeaderTextField = (typeof HEADER_TEXT_FIELDS)[number]

export function placeholderValues(
  context: ExportContext,
  report: { name: string; code: string },
): Record<PlaceholderKey, string> {
  return {
    'station.name': context.station.name,
    'station.code': context.station.code,
    'register.name': report.name,
    'register.code': report.code,
    'period.from': context.period.from ? formatFormDate(context.period.from) : 'start',
    'period.to': context.period.to ? formatFormDate(context.period.to) : 'today',
    records: String(context.records),
    'generated.by': `${context.generatedBy.name} (${context.generatedBy.employeeId})`,
    'generated.at': formatStampSeconds(context.generatedAt),
  }
}

/** Replaces known placeholders with plain text. Unknown ones stay as typed (saving is blocked on them). */
export function fillPlaceholders(text: string, values: Record<PlaceholderKey, string>): string {
  return text.replace(TOKEN, (match, key: string) => (KNOWN.has(key) ? values[key as PlaceholderKey] : match))
}

function problemsIn(text: string, max: number): string[] {
  const problems: string[] = []
  for (const [, key] of text.matchAll(TOKEN)) {
    if (!KNOWN.has(key)) problems.push(`{${key}} is not a placeholder. Use one of the buttons to insert one.`)
  }
  if (text.length > max) problems.push(`Keep this under ${max} characters (now ${text.length}).`)
  return problems
}

/** Problems per field; an empty object means the template can be saved. */
export function validateHeader(content: HeaderContent): Partial<Record<HeaderTextField, string[]>> {
  const result: Partial<Record<HeaderTextField, string[]>> = {}
  if (!content.title.trim()) result.title = ['Give the report a title, e.g. {register.name}.']
  for (const field of HEADER_TEXT_FIELDS) {
    if (result[field]) continue
    const problems = problemsIn(content[field], MAX_FIELD_LENGTH)
    if (problems.length) result[field] = problems
  }
  return result
}
