import { STATUS_LABELS } from './constants'
import type { ShiftDiary } from './types'
import { formatFormDate, formatStamp } from './utils'

export interface TableExportMeta {
  stationName: string
  stationCode: string
  from: string
  to: string
  shift?: string
  status?: string
  generatedBy?: { name: string; employeeId?: string }
}

const HEADERS = [
  'Date',
  'Shift',
  'Station',
  'Station Controller',
  'Emp ID',
  'Entries',
  'Status',
  'Handed over by',
  'Taken over by',
  'Handed over at',
]

function rows(diaries: ShiftDiary[]): string[][] {
  return diaries.map((d) => [
    formatFormDate(d.date),
    d.shift,
    d.stationCode,
    d.controller?.name ?? '',
    d.controller?.employeeId ?? '',
    String(d.entries.length),
    STATUS_LABELS[d.status],
    d.handover.handedBy?.name ?? '',
    d.handover.takenBy?.name ?? '',
    d.handover.handedAt ? formatStamp(d.handover.handedAt) : '',
  ])
}

function buildMetaLines(meta?: TableExportMeta, totalCount?: number): string[][] {
  if (!meta) return []
  return [
    ['CHENNAI METRO RAIL LIMITED'],
    ['STATION SHIFT DIARY REGISTER — SHIFT SUMMARY'],
    [`Station: ${meta.stationName} (${meta.stationCode})`],
    [
      `Period: ${formatFormDate(meta.from)} to ${formatFormDate(meta.to)} | Shift: ${meta.shift || 'All shifts'} | Status: ${meta.status || 'All statuses'}`,
    ],
    [
      `Generated by: ${meta.generatedBy?.name ?? 'Staff'}${meta.generatedBy?.employeeId ? ` (${meta.generatedBy.employeeId})` : ''} on ${formatStamp(new Date().toISOString())} | Total Records: ${totalCount ?? 0}`,
    ],
    [],
  ]
}

/** Tab-separated with official template header, pastes straight into Excel or email. */
export function toTsv(diaries: ShiftDiary[], meta?: TableExportMeta): string {
  const metaLines = buildMetaLines(meta, diaries.length)
  return [...metaLines, HEADERS, ...rows(diaries)].map((r) => r.join('\t')).join('\n')
}

const csvCell = (value: string) => (/[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value)

/** Excel-compatible CSV in official CMRL template format (with BOM so ₹ and names open correctly). */
export function downloadCsv(diaries: ShiftDiary[], fileName: string, meta?: TableExportMeta) {
  const metaLines = buildMetaLines(meta, diaries.length)
  const csv = [...metaLines, HEADERS, ...rows(diaries)].map((r) => r.map(csvCell).join(',')).join('\r\n')
  const url = URL.createObjectURL(new Blob(['\ufeff', csv], { type: 'text/csv;charset=utf-8' }))
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.append(link)
  link.click()
  link.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 10_000)
}
